language: java
script: gradle clean build 
install:
  - gradle test
script:
  - export COVERALLS_REPO_TOKEN=BY4EoH4btivMXxdaOAhbPMaBtbpGrmdAe
after_success:
  - ./gradlew check jacocoTestReport coveralls
  
jdk: oraclejdk8